# Generated by capnp version: <generated version info>
# DO NOT EDIT
import capnp
capnp.remove_import_hook()

import os as _os
import sys as _sys
import capnp as _capnp

this_dir = _os.path.dirname(__file__)

# modify your path!
bintrace_capnp = _capnp.load('/home/user/Desktop/web/backend/fuzzers/fuzzware/emulator/harness/fuzzware_harness/tracing/bintrace.capnp', imports=[this_dir])

TraceEvent = bintrace_capnp.TraceEvent
Crash = bintrace_capnp.Crash
Instruction = bintrace_capnp.Instruction
Registers = bintrace_capnp.Registers
Access = bintrace_capnp.Access
AccessTarget = bintrace_capnp.AccessTarget
